core/urls.py
from django.urls import path
from .views import (
    DoctorDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    proceed_payment,
    checkout_success
)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('bookings/<int:pk>', CheckoutView.as_view(), name='booking'),
    path('bookings/<int:pk>/proceed-payment', proceed_payment, name='booking-proceed-payment'),
    path('checkout/success/', checkout_success, name='checkout-success'),
    path('booking-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('doctor/<str:slug>/<int:pk>/', DoctorDetailView.as_view(), name='product'),
]

from schema_graph.views import Schema
urlpatterns += [
    # On Django 2+:
    path("schema/", Schema.as_view()),
]

core/models.py
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse
from django_countries.fields import CountryField
from django.utils.text import slugify



LABEL_CHOICES = (
    ('P', 'danger'),
    ('S', 'secondary'),
    ('D', 'primary')
)

TITLE_MAP = {
        'P': 'Professor',
        'S': 'PhD',
        'D': 'Dr.'
        }

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)


def construct_color_map():
    COLOR_CONSTRUCTOR = {
            'purple': ['dermatology'],
            'primary-color': ['ophthalmology'],
            'secondary-color': ['internal-medicine'],
            'danger-color': ['surgery'],
            }
    res = {}
    for color, affected_list in COLOR_CONSTRUCTOR.items():
        for i in affected_list:
            res[i] = color
    return res

BADGE_COLOR_MAP = construct_color_map()


class Specialty(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=100, unique=True)


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Specialty, self).save(*args, **kwargs)



    def __str__(self):
        return self.name


    @property
    def badge_color(self):
        return BADGE_COLOR_MAP[self.slug] if self.slug in BADGE_COLOR_MAP else 'primary-color'

class Doctor(models.Model):
    name = models.CharField(max_length=100)
    price = models.FloatField()
    specialties = models.ManyToManyField(Specialty)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField()

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Doctor, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'pk': self.pk,
            'slug': self.slug,
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_booking_url(self):
        return reverse("core:booking", kwargs={
            'pk': self.pk
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })

    @property
    def short_description(self):
        return self.description[:100]

    def title(self):
        return TITLE_MAP[self.label]


class Booking(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    booked_date = models.DateTimeField(auto_now_add=True)
    payment_date = models.DateTimeField(default=None, null=True)
    examination_date = models.DateTimeField()
    address = models.CharField(max_length=500)
    total = models.FloatField(default=0)
    description = models.TextField(default='', null=True, blank=True)


    def get_proceed_payment_url(self):
        return reverse('core:booking-proceed-payment', kwargs={'pk': self.pk})


def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">

  <!-- Moment.js -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js" integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>

  <!-- Tempus Dominus Bootstrap 4 -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>

  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }
    .item-img {
      max-width: 100%;
      height: 350px;
      object-fit: cover;
      object-position: center;
    }

  </style>
</head>

{% include "navbar.html" %}

<body>

    <div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
    </div>

    {% block content %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock %}

    {% include "footer.html" %}
    {% include "scripts.html" %}

    {% block extra_scripts %}
    {% endblock extra_scripts %}
</body>
</html>

templates/booking-new.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

  <main >
    <div class="container wow fadeIn">
      <h2 class="my-5 h2 text-center">Booking Form</h2>
      <div class="row">
        <div class="col-md-8 mb-4">
          <div class="card">
            <form method="POST" class="card-body">
              {% csrf_token %}

              <h3>Choose time</h3>
              <div class="input-group date mb-2" id="datetimepicker1" data-target-input="nearest">
                <input type="text" class="form-control datetimepicker-input" data-target="#datetimepicker1" name="examination_date" required/>
                <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
                  <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                </div>
              </div>
              <iframe id="gmap" src="{% static 'gg_map.html' %}"
                      width="100%" height="500px"
                                   style="border:0;"
                                   loading="lazy" class="border border-primary">
              </iframe>


              <h3 id="show-address">Address: </h3>
              <input type="hidden" name="address" required/>
              <button id="confirm-address" class="btn btn-primary" type="button">Confirm address</button>

              <h3>Describe your problem: </h3>
              <textarea class="form-control" name="description" id="exampleFormControlTextarea1" rows="3" required></textarea>
              <!-- <h3>Which medical specialties you want to examine?</h3> -->

              <hr>

              <h3>Payment option</h3>

              <div class="d-block my-3">
                {% for value, name in form.fields.payment_option.choices %}
                <div class="custom-control custom-radio">
                  <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio" class="custom-control-input" required>
                  <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
                </div>
                {% endfor %}
              </div>

              <hr class="mb-4">
              <div class="text-center mb-2">
                Total: ${{ doctor.price }}
              </div>
              <button class="btn btn-primary btn-lg btn-block" type="submit">Book and proceed payment</button>

            </form>

          </div>

        </div>

        <div class="col-md-4 mb-4">
          {% include "booking_snippet.html" %}
        </div>

      </div>

    </div>
  </main>

{% endblock content %}
{% block extra_scripts %}
<script>
$('#show-address').hide();
$('#confirm-address').on('click', function() {
  var search_input = $('#gmap').contents().find('#location-search-input').val();
  if (search_input) {
      if(confirm(`Are you sure you address is ${search_input}`)) {
          $('input[name=address]').val(search_input);
          $('#show-address').html(`Address: ${search_input}`);
          $('#show-address').show();
          $('#gmap').hide();
          $(this).hide();
        }
  }
})
</script>
{% endblock %}

templates/booking_snippet.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Doctor Info</span>
    <span class="badge badge-secondary badge-pill">{{ doctor.title }}</span>
    </h4>
    <div>
        <div class="card">
          <img class="card-img-top" src="{{ doctor.image.url }}" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">
        {{ doctor.name }}
      </h5>
      <div class="mb-2">
        Specialties:
        {% for specialty in doctor.specialties.all %}
        <span class="badge {{specialty.badge_color}}">{{ specialty }}</span>
        {% endfor %}
      </div>
      <p class="card-text">{{ doctor.description }}</p>
    </div>
  </div>
    </div>

    {% if DISPLAY_COUPON_FORM %}
    <form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
        {% csrf_token %}
        <div class="input-group">
            {{ couponform.code }}
            <div class="input-group-append">
            <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
            </div>
        </div>
    </form>
    {% endif %}

</div>

templates/doctor.html
{% extends "base.html" %}

{% block content %}

  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="{{ object.image.url }}" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">
            <h5>
              <strong>
                <a href="{{ object.get_absolute_url }}" class="dark-grey-text">{{ object.name }}
                  <span class="badge badge-pill {{ object.get_label_display }}-color">{{ object.title }}</span>
                </a>
              </strong>
            </h5>

            <div class="mb-3">
              {% for specialty in object.specialties.all %}
              <a href="">
                <span class="badge {{ specialty.badge_color }} mr-1">{{ specialty }}</span>
              </a>
              {% endfor %}
            </div>

            <p class="lead">
              {% if object.discount_price %}
              <span class="mr-1">
                <del>${{ object.price }}</del>
              </span>
              <span>${{ object.discount_price }}</span>
              {% else %}
              <span>${{ object.price }}</span>
              {% endif %}
            </p>

            <p class="lead font-weight-bold">{{ object.title }}</p>

            <p>{{ object.description }}</p>

            {% comment %} <form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">
                Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form> {% endcomment %}
            <a href="{{object.get_booking_url}}" class="btn btn-primary btn-md my-0 p">
              Book
              <i class="fas fa-calendar ml-1"></i>
            </a>
          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Recommended Doctors</h4>

          <p>Finding the best doctor that fits you or your family’s needs is one of the most important things you can do for your health. BK MEC Doctors are considered the best doctors in their area of specialty and expertise. Here you can find the best doctors by specialty.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        {% for item in items %}
          <div class="col-lg-4 col-md-12 mb-4">

            <a href="{{ item.get_absolute_url }}">
              <img src="{{ item.image.url }}" class="img-fluid item-img" alt="">
            </a>

          </div>
        {% endfor %}


      </div>
      <!--Grid row-->

    </div>
  </main>

{% endblock content %}

templates/home.html
{% extends "base.html" %}

{% block content %}
<!-- <iframe id="location" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7839.127219342677!2d106.66432977360002!3d10.76807656930862!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752ee3f654b829%3A0xa2dd4a3f680e3d79!2zSMOyYSBI4bqjbyBIb3NwaXRhbA!5e0!3m2!1svi!2s!4v1669864846413!5m2!1svi!2s" width="500" height="500" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"> -->
<!-- </iframe> -->
<!-- <select name="cars" id="map-picker"> -->
<!--   <option value=""></option> -->
<!--   <option value="!1m18!1m12!1m3!1d3919.511579557385!2d106.65571311532!3d10.772074992324535!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752ec3c161a3fb%3A0xef77cd47a1cc691e!2sHo%20Chi%20Minh%20City%20University%20of%20Technology%20(HCMUT)!5e0!3m2!1sen!2s!4v1670160836802!5m2!1sen!2s -->
<!-- ">DH Bach khoa</option> -->
<!-- </select> -->
  <main>
  <!--Carousel Wrapper-->
  <div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">

    <!--Indicators-->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-1z" data-slide-to="1"></li>
      <li data-target="#carousel-example-1z" data-slide-to="2"></li>
    </ol>
    <!--/.Indicators-->

    <!--Slides-->
    <div class="carousel-inner" role="listbox">

      <!--First slide-->
      {% for doctor in recommended_doctors %}
      {% endfor %}
      <div class="carousel-item active">
        <div class="view" style="background-image: url('https://post.medicalnewstoday.com/wp-content/uploads/sites/3/2022/11/1296x728-Header-podcast-viagra-2-1024x576.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Medical News</strong>
              </h1>

              <h3>
                <strong>In Conversation: How Viagra became a new 'tool' for young men</strong>
              </h3>

              <a target="_blank" href="https://www.medicalnewstoday.com/articles/in-conversation-how-viagra-became-a-new-tool-for-young-men" class="btn btn-outline-white btn-lg">Read
                <i class="fas fa-book ml-2"></i>
              </a>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/First slide-->

      <!--Second slide-->
      <div class="carousel-item">
        <div class="view" style="background-image: url('https://post.medicalnewstoday.com/wp-content/uploads/sites/3/2022/11/Vaccines_dementia_GettyImages1277352629_Header-1024x575.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Medical News</strong>
              </h1>

              <h3>
                <strong>Dementia vaccines: What are they, and when could they become available?</strong>
              </h3>

              <a target="_blank" href="https://www.medicalnewstoday.com/articles/dementia-vaccines-what-are-they-and-when-could-they-become-available" class="btn btn-outline-white btn-lg">Read
                <i class="fas fa-book ml-2"></i>
              </a>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/Second slide-->

      <!--Third slide-->
      <div class="carousel-item">
        <div class="view" style="background-image: url('https://post.medicalnewstoday.com/wp-content/uploads/sites/3/2022/12/brain-scan-lecanemab-Alzheimers-header-1024x575.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Medical News</strong>
              </h1>

              <h3>
                <strong>Lecanemab: Why a new Alzheimer's drug has drawn praise and some concern</strong>
              </h3>

              <a target="_blank" href="https://www.medicalnewstoday.com/articles/lecanemab-why-a-new-alzheimers-drug-has-drawn-praise-and-some-concern" class="btn btn-outline-white btn-lg">Read
                <i class="fas fa-book ml-2"></i>
              </a>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/Third slide-->

    </div>
    <!--/.Slides-->

    <!--Controls-->
    <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
    <!--/.Controls-->

  </div>
  <!--/.Carousel Wrapper-->    

    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Specialties:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item {% if filter_specialty is None %}active{% endif %}">
              <a class="nav-link" href="{% url 'core:home'  %}">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            {% for specialty in specialties %}
            <li class="nav-item {% if specialty == filter_specialty %} active {% endif %}">
              <a class="nav-link" href="?specialty={{ specialty.slug }}">{{ specialty }}</a>
            </li>
            {% endfor %}
          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" name="search" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <div class="row wow fadeIn">

          {% for item in object_list %}
          <div class="col-lg-3 col-md-6 mb-4">

            <div class="card h-100">

              <div class="view overlay">
                {% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top" {% endcomment %}
                <img src="{{ item.image.url }}" class="card-img-top item-img">
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>

              <div class="card-body text-center">
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.name }}
                      <span class="badge badge-pill {{ item.get_label_display }}-color">{{ item.title }}</span>
                    </a>
                  </strong>
                </h5>
                <p>{{ item.short_description }}...</p>

                <h4 class="font-weight-bold blue-text">
                  <strong>$
                  {{ item.price }}
                  </strong>
                </h4>

              </div>

            </div>

          </div>
          {% endfor %}
        </div>

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->

      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
              <span class="sr-only">(current)</span>
            </a>
          </li>

          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}

    </div>
  </main>
  <script>
    $('#map-picker').on('change', function(){
          url = 'https://www.google.com/maps/embed?pb=';
          url = url + $(this).val();
          $('#location').attr('src', url);
        })

  </script>

{% endblock content %}

templates/navbar.html
{% load cart_template_tags %}

<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="/">
        <strong class="blue-text">BK-MEC</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          {% comment %} <li class="nav-item active">
            <a class="nav-link waves-effect" href="/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="/checkout">
            Checkout</a>
          </li> {% endcomment %}
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'core:order-summary' %}" class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> {{ request.user|booking_count }} </span>
              <i class="fas fa-calendar"></i>
              <span class="clearfix d-none d-sm-inline-block"> Welcome, {{ request.user }} </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
              <span class="clearfix d-none d-sm-inline-block"> Logout </span>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_login' %}">
              <span class="clearfix d-none d-sm-inline-block"> Login </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
              <span class="clearfix d-none d-sm-inline-block"> Signup </span>
            </a>
          </li>
          {% endif %}
        </ul>
      </div>

    </div>
  </nav>

templates/request_refund.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <main>
    <div class="container">

    <h2>Request Refund</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class='btn btn-primary'>Submit</button>
    </form>

    </div>
  </main>

{% endblock content %}

templates/scripts.html
{% load static %}
  
<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
  // Animations initialization
  new WOW().init();

</script>